// src/components/LayoutCard.tsx
import { Button } from "./ui/button";
import { Card, CardContent, CardHeader } from "./ui/card";

interface Props {
  id: string;          // layout id returned by backend
  thumbUrl: string;    // static png generated by FastAPI
  timing: number;      // WNS or total power
  onSimulate: (id: string)=>void;
}

export default function LayoutCard({ id, thumbUrl, timing, onSimulate }: Props) {
  return (
    <Card className="hover:shadow-xl transition-shadow duration-200">
      <CardHeader>
        <h3 className="text-lg font-semibold">Layout #{id.slice(0, 8)}</h3>
      </CardHeader>
      <CardContent className="flex flex-col items-center gap-4">
        <img src={thumbUrl} alt={`layout ${id}`} className="w-full rounded-xl" />
        <p className="text-sm text-muted-foreground">Power: {timing.toFixed(2)} mW</p>
        <Button onClick={()=>onSimulate(id)} className="w-full">Simulate</Button>
      </CardContent>
    </Card>
  );
}